// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLLOa5pvWwBffz3HtCuljjCjfozgqEdpc',
    appId: '1:70457019801:web:bf52fbaffa67a97383d708',
    messagingSenderId: '70457019801',
    projectId: 'todo-b552a',
    authDomain: 'todo-b552a.firebaseapp.com',
    storageBucket: 'todo-b552a.appspot.com',
    measurementId: 'G-0M3GRXE6FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgPwvF8ZT8Tfu0_oIMh0dEqmIh_fcdF-E',
    appId: '1:70457019801:android:14db63512e020e8883d708',
    messagingSenderId: '70457019801',
    projectId: 'todo-b552a',
    storageBucket: 'todo-b552a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzDCT5AiiyNQyFGR6pmGFHgYPVb_LvCcw',
    appId: '1:70457019801:ios:d12df44fdde408f183d708',
    messagingSenderId: '70457019801',
    projectId: 'todo-b552a',
    storageBucket: 'todo-b552a.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzDCT5AiiyNQyFGR6pmGFHgYPVb_LvCcw',
    appId: '1:70457019801:ios:d12df44fdde408f183d708',
    messagingSenderId: '70457019801',
    projectId: 'todo-b552a',
    storageBucket: 'todo-b552a.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLLOa5pvWwBffz3HtCuljjCjfozgqEdpc',
    appId: '1:70457019801:web:fc3b5ac44ce94cca83d708',
    messagingSenderId: '70457019801',
    projectId: 'todo-b552a',
    authDomain: 'todo-b552a.firebaseapp.com',
    storageBucket: 'todo-b552a.appspot.com',
    measurementId: 'G-4LNR47YBEY',
  );

}